name: On PR from AutoNews

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add label 'auto-news'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: auto-news
